class_name Names
extends Node

static func generate_customer_name() -> String:
    return "%s %s" % [RandomUtils.pick_random(Names.customer_adjectives), RandomUtils.pick_random(Names.customers)]


const customers: Array[String] = [
    "John",
    "Joe",
    "Mac",
    "Bobby",
    "Jane",
    "Juliet",
    "Joseph",
    "Samuel",
    "Sophie",
    "Sally",
    "Ademar",
    "Alaric",
    "Aldhelm",
    "Baldwin",
    "Bartholomew",
    "Bertram",
    "Cedric",
    "Conan",
    "Cuthbert",
    "Edgar",
    "Edmund",
    "Eadric",
    "Eadwig",
    "Godfrey",
    "Harold",
    "Leofric",
    "Nigel",
    "Osbert",
    "Oswald",
    "Radulf",
    "Ranulf",
    "Reginald",
    "Roland",
    "Rolf",
    "Sigismund",
    "Tostig",
    "Ulric",
    "Waleran",
    "Walthari",
    "Wilfred",
    "Winfrid",
    "Wymond",
    "William",
    "Yves",
    "Alwi",
    "Andry",
    "Arnger",
    "Ashwy",
    "Brunwine",
    "Cadell",
    "Caro",
    "Dagmar",
    "Edwy",
    "Gebwin",
    "Gunther",
    "Halfdan",
    "Ingram",
    "Jaromir",
    "Nantelm",
    "Oswin",
    "Reinmar",
    "Saracen",
    "Sinister",
    "Sulon",
    "Theodwin",
    "Wilenc",
    "Elric",
    "Hamo",
    "Hann",
    "Herry",
    "Hob",
    "Hopkin",
    "Hudde",
    "Ilbert",
    "Jackin",
    "Jan",
    "Jankin",
    "Judd",
    "Kinborough",
    "Larkin",
    "Law",
    "Mack",
    "Morris",
    "Nichol",
    "Noll",
    "Ode",
    "Pate",
    "Randel",
    "Ranulf",
    "Rohese",
    "Roul",
    "Royse",
    "Stace",
    "Tenney",
    "Wilkin",
    "Wilky",
    "Wilmot",
    "Wybert",
    "Wymond",
    "Wyot",
    "Adalhilde",
    "Adalsinde",
    "Aitla",
    "Erlinde",
    "Eulalia",
    "Fritheburg",
    "Gislilde",
    "Guimar",
    "Idony",
    "Ingalsinde",
    "Liutlinde",
    "Madwen",
    "Nantelma",
    "Petra",
    "Saidra",
    "Soave",
    "Thecla",
    "Wendela",
    "Ysoria ",
    "Bridgette",
    "Tove",
    "Marjatta",
    "Irmeni ",
    "Millicent ",
    "Alys",
    "Ayleth ",
    "Anastas ",
    "Alianor ",
    "Cedany ",
    "Ellyn",
    "Helewys",
    "Malkyn",
    "Peronell ",
    "Sybbyl",
    "Ysmay",
    "Thea ",
    "Jacquelyn ",
    "Amelia ",
    "Gloriana ",
    "Catherine",
    "Anne",
    "Mary",
    "Arabella ",
    "Elizabeth ",
    "Hildegard ",
    "Brunhild ",
    "Adelaide ",
    "Alice ",
    "Beatrix ",
    "Cristiana ",
    "Eleanor ",
    "Emeline ",
    "Isabel ",
    "Juliana ",
    "Margaret ",
    "Matilda ",
    "Mirabelle ",
    "Rose ",
    "Helena ",
    "Guinevere ",
    "Isolde ",
    "Maerwynn ",
    "Muriel ",
    "Winifred ",
    "Godiva ",
    "Catrain ",
    "Angmar ",
    "Gussalen ",
    "Jasmine ",
    "Josselyn ",
    "Maria ",
    "Victoria ",
    "Gwendolynn ",
    "Enndolynn ",
    "Janet ",
    "Luanda ",
    "Krea ",
    "Rainydayas ",
    "Atheena ",
    "Dimia ",
    "Phrowenia",
    "Aleida ",
    "Ariana ",
    "Alexia ",
    "Katelyn ",
    "Katrina ",
    "Loreena ",
    "Kaylein ",
    "Seraphina ",
    "Duraina ",
    "Ryia ",
    "Farfelee ",
    "Iseult",
    "Benevolence ",
    "Brangian ",
    "Elspeth ",
    "Agatha",
    "Aelith",
    "Alice",
    "Althea",
    "Amabel",
    "Anice",
]

const customer_adjectives: Array[String] = [
    "Adventurous",
    "Affectionate",
    "Agile",
    "Alert",
    "Amiable",
    "Ambitious",
    "Analytical",
    "Angelic",
    "Appreciative",
    "Articulate",
    "Assertive",
    "Attentive",
    "Authentic",
    "Brave",
    "Bright",
    "Calm",
    "Candid",
    "Careful",
    "Caring",
    "Cheerful",
    "Charming",
    "Compassionate",
    "Considerate",
    "Crazy",
    "Creative",
    "Curious",
    "Dauntless",
    "Diligent",
    "Dynamic",
    "Energetic",
    "Enthusiastic",
    "Exuberant",
    "Fair-minded",
    "Fearless",
    "Focused",
    "Generous",
    "Gentle",
    "Graceful",
    "Hardworking",
    "Helpful",
    "Honest",
    "Humble",
    "Humorous",
    "Imaginative",
    "Innovative",
    "Joyful",
    "Jolly",
    "Kind",
    "Loyal",
    "Magnanimous",
    "Mature",
    "Merciful",
    "Modest",
    "Motivated",
    "Patient",
    "Peaceful",
    "Persistent",
    "Playful",
    "Polite",
    "Positive",
    "Practical",
    "Proud",
    "Reliable",
    "Resilient",
    "Resourceful",
    "Responsible",
    "Sincere",
    "Skilled",
    "Smart",
    "Spirited",
    "Steady",
    "Strong-willed",
    "Thoughtful",
    "Tolerant",
    "Trustworthy",
    "Understanding",
    "Wise",
    "Warm-hearted",
]


